
name = "jessicadhg-pais-agem"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[vars]
RESEND_API_KEY = "re_CwKRV8ZW_GK4GEqLnRWEJW27Mz45weiyJ"
JESSICA_EMAIL = "contact@jessicadahorta.com"
