name = "api-worker"
main = "./contact.js"
compatibility_date = "2024-11-01"
account_id = "08ab16b3d302d2e0bb34440c012943b9"

[vars]
JESSICA_EMAIL = "contact@jessicadahorta.com"
# RESEND_API_KEY is set via Cloudflare Pages dashboard as a Secret
